import axios from 'axios';

export const ADD_DONATION_START = 'ADD_DONATION_START ';
export const ADD_DONATION_SUCCESS = 'ADD_DONATION_SUCCESS';
export const ADD_DONATION_FAILURE = 'ADD_DONATION_FAILURE';

export const EDIT_DONATION_START = 'EDIT_DONATION_START ';
export const EDIT_DONATION_SUCCESS = 'EDIT_DONATION_SUCCESS';
export const EDIT_DONATION_FAILURE = 'EDIT_DONATION_FAILURE';

export const DELETE_DONATION_START = 'DELETE_DONATION_START ';
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS';
export const DELETE_DONATION_FAILURE = 'DELTE_DONATION_FAILURE';

export const GET_SCHOOL_DONATIONS_START = 'GET_SCHOOL_DONATIONS_START';
export const GET_SCHOOL_DONATIONS_SUCCESS = 'GET_SCHOOL_DONATIONS_SUCCESS';
export const GET_SCHOOL_DONATIONS_FAILURE = 'GET_SCHOOL_DONATIONS_FAILURE';

export const GET_ALL_DONATIONS_SCHOOL_START = 'GET_ALL_DONATIONS_SCHOOL_START';
export const GET_ALL_DONATIONS_SCHOOL_SUCCESS = 'GET_ALL_DONATIONS_SCHOOL_SUCCESS';
export const GET_ALL_DONATIONS_SCHOOL_FAILURE = 'GET_ALL_DONATIONS_SCHOOL_FAILURE';

export const GET_SCHOOL_DONATIONS_START_2 = 'GET_SCHOOL_DONATIONS_START_2';
export const GET_SCHOOL_DONATIONS_SUCCESS_2 = 'GET_SCHOOL_DONATIONS_SUCCESS_2';
export const GET_SCHOOL_DONATIONS_FAILURE_2 = 'GET_SCHOOL_DONATIONS_FAILURE_2';