import axios from 'axios';

export const EDIT_USER_START = 'EDIT_USER_START ';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_FAILURE ';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const USER_DONATIONS_START = 'USER_DONATIONS_START';
export const USER_DONATIONS_SUCCESS = 'USER_DONATIONS_SUCCESS';
export const USER_DONATIONS_FAILURE = 'USER_DONATIONS_FAILURE';